require('plugins')
require('settings')
require('keymaps')
require('theme')
require('lsp.setup')
require('plug-config.nvim-cmp')
require('plug-config.floaterm')
require('plug-config.dashboard')
require('plug-config.vimwiki')
require('plug-config.barbar')

