#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_border               off
yabai -m config window_border_width         5
yabai -m config active_window_border_color  '0xffc4a7e7'
yabai -m config normal_window_border_color  '0xff6e6a86'

apps='^(iTerm2|Google Chrome|PDF Expert|WPS Office|Code)$'
yabai -m rule --add app!="${apps}" manage=off
yabai -m rule --add app="^WPS Office$" space=2
yabai -m rule --add app="^PDF Expert$" space=2
yabai -m rule --add app="^QQ$" space=4
yabai -m rule --add app="^WeChat$" space=4
yabai -m rule --add app="^WeCom$" space=4
yabai -m rule --add app="^YesPlayMusic$" space=5

# general settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               7
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   6

echo "yabai configuration loaded.."
