#!/bin/bash

# launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# window focus
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

# custom sketchybar events
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

yabai -m config window_shadow float

yabai -m config auto_balance off
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow on

yabai -m config --space 4 layout float

apps='^(Warp|ChatGPT|MATLAB|diagrams.net|Alacritty|Obsidian|YouTube|yuhi|Google Chrome Canary|WPS Office|Safari|Firefox|VimR|kitty|Google Chrome|PDF Expert|Code|Microsoft Word|Microsoft Excel|Microsoft PowerPoint)$'
yabai -m rule --add app!="${apps}" manage=off
yabai -m rule --add app="^Microsoft Word$" title="^Word$" manage=off
yabai -m rule --add app="^Microsoft Word$" title="^$" manage=off
yabai -m rule --add app="^Microsoft Word$" title="^字数统计$" manage=off
yabai -m rule --add app="^Microsoft Word$" title="^Word 偏好设置$" manage=off
yabai -m rule --add app="^PDF Expert$" title="^偏好设置$" manage=off
yabai -m rule --add app="^MATLAB$" title="^Figure" manage=off
yabai -m rule --add app="^Google Chrome$" title="^DevTools" manage=off
yabai -m rule --add app="^kitty$" opacity=0.9
yabai -m rule --add app="^Alacritty$" opacity=0.9
yabai -m rule --add app="^Warp$" opacity=0.9
# yabai -m rule --add app="^Obsidian$" opacity=0.9
yabai -m rule --add app="^微信$" space=4
yabai -m rule --add app="^Telegram$" space=4
yabai -m rule --add app="^QQ$" space=4
yabai -m rule --add app="^企业微信$" space=4
yabai -m rule --add app="^音乐$" space=4
yabai -m rule --add app="^Spotify$" space=4
yabai -m rule --add app="^Steam$" space=4

# make JetBrains Apps popup windows float
# JB_Apps='^(IntelliJ IDEA)$'
# yabai -m rule --add app="${JB_Apps}" manage=off
# # If `Open last project when launch` is checked, add this rule. And make sure `always show project path` is also checked.
# # yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on 
# yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on


# window opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# general settings
yabai -m config layout                       bsp
yabai -m config top_padding                  32
yabai -m config bottom_padding               9
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   9
