#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# window focus
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

# custom sketchybar events
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

# yabai border
yabai -m config window_border               off
yabai -m config window_border_width         4
yabai -m config active_window_border_color  '0xfff6c177'
yabai -m config normal_window_border_color  '0xff908caa'

yabai -m config auto_balance off
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow on

yabai -m config --space 4 layout float
yabai -m config --space 5 layout float

apps='^(diagrams.net|Alacritty|Obsidian|YouTube|yuhi|Google Chrome Canary|WPS Office|Safari|Firefox|IntelliJ IDEA|VimR|kitty|Google Chrome|PDF Expert|Code|Microsoft Word|Microsoft Excel|Microsoft PowerPoint)$'
yabai -m rule --add app!="${apps}" manage=off border=off
yabai -m rule --add app="^Microsoft Word$" title="^Word$" manage=off border=off
yabai -m rule --add app="^Microsoft Word$" title="^$" manage=off border=off
yabai -m rule --add app="^Microsoft Word$" title="^字数统计$" manage=off border=off
yabai -m rule --add app="^Microsoft Word$" title="^Word 偏好设置$" manage=off border=off
yabai -m rule --add app="^PDF Expert$" title="^偏好设置$" manage=off border=off
yabai -m rule --add app="^QQ$" space=4
yabai -m rule --add app="^kitty$" opacity=0.9
yabai -m rule --add app="^Obsidian$" opacity=0.95
yabai -m rule --add app="^Code$" opacity=0.95
yabai -m rule --add app="^微信$" space=4
yabai -m rule --add app="^企业微信$" space=4
# yabai -m rule --add app="^QSpace Pro$" layer=above  # topmost
yabai -m rule --add app="^音乐$" space=5
yabai -m rule --add app="^YesPlayMusic$" space=5
yabai -m rule --add app="^Steam$" space=5
yabai -m rule --add app="^Firefox$" title="^Library$" manage=off border=off
yabai -m rule --add app="^Firefox$" title="^$" manage=off border=off
yabai -m rule --add app="^Firefox$" title="^Extension" manage=off border=off
yabai -m rule --add app="^IntelliJ IDEA$" title="Preferences|New.*|.*Welcome*.|Keyboard.*|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*." manage=off border=off

# window opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

# general settings
yabai -m config layout                       bsp
yabai -m config top_padding                  32
yabai -m config bottom_padding               7
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   9

echo "yabai configuration loaded.."
